### ISSUE TITLE
Diapositive

### ISSUE THREAD

**Issue by foxyseta** [cartabinaria/emerging-programming-paradigms#1]
@timmykill grazie mille :) Questo insegnamento mi ha sempre ispirato un sacco. Per caso hai anche le diapositive da caricare? Avrei voluto seguire questo corso ma non sto facendo la magistrale a Bologna.

**Comment by timmykill** [comment]
Ho scrapato il virtuale e sto facendo appunti per dare l'esame.
Non so quanto possa esserti utile personalmente tho, visto che Coen usa virtuale un po' come dump di informazioni a caso e tende a non seguire in modo lineare le slides

**Comment by foxyseta** [comment]
Beh mi piacerebbe solo vedere gli argomenti e non devo dare l'esame ovviamente, quindi va più che bene. In bocca al lupo per l'esame!
